import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

function Day19() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-950 via-slate-900 to-slate-950 text-white">

      <Navbar />

      {/* Hero Section */}
      <section className="pt-36 pb-20 text-center px-6">

        <p className="text-blue-400 uppercase tracking-widest">
          Day 19 Submission
        </p>

        <h1 className="text-5xl md:text-6xl font-bold mt-4">
          Candidate Shortlisting System
        </h1>

        <p className="text-gray-400 mt-6 max-w-4xl mx-auto text-lg">
          Implemented the candidate shortlisting workflow by connecting
          ATS scores with automated recruitment decisions and validating
          the recruitment API using candidate scoring scenarios.
        </p>

        <div className="mt-10 flex flex-wrap justify-center gap-5">

          {/* PDF Button */}
          <a
            href="/day19_completed.pdf"
            target="_blank"
            rel="noopener noreferrer"
            className="px-8 py-4 bg-blue-600 hover:bg-blue-700 rounded-xl font-semibold transition"
          >
            📄 View Day 19 Report
          </a>

          <a
            href="#implementation"
            className="px-8 py-4 border border-gray-600 hover:bg-slate-800 rounded-xl font-semibold transition"
          >
            Explore Implementation
          </a>

        </div>

      </section>

      {/* Documentation */}
      <section className="max-w-5xl mx-auto px-6 py-16">

        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-8 md:p-10 text-center">

          <p className="text-blue-400 uppercase tracking-widest">
            Internship Deliverable
          </p>

          <h2 className="text-3xl md:text-4xl font-bold mt-4">
            📄 Day 19 Documentation Report
          </h2>

          <p className="text-gray-400 mt-6">
            Technical documentation covering ATS scoring,
            candidate shortlisting, decision logic, API validation,
            troubleshooting, and developer knowledge transfer.
          </p>

          <div className="flex flex-wrap justify-center gap-5 mt-8">

            <a
              href="/day19_completed.pdf"
              target="_blank"
              rel="noopener noreferrer"
              className="px-6 py-3 bg-blue-600 hover:bg-blue-700 rounded-xl font-semibold transition"
            >
              👁️ View PDF
            </a>

            <a
              href="/day19_completed.pdf"
              download="day19_completed.pdf"
              className="px-6 py-3 border border-gray-600 hover:bg-slate-800 rounded-xl font-semibold transition"
            >
              ⬇️ Download Day 19
            </a>

          </div>

        </div>

      </section>

      {/* Implementation */}
      <section
        id="implementation"
        className="max-w-7xl mx-auto px-6 pb-24"
      >

        <div className="text-center mb-14">

          <p className="text-blue-400 uppercase tracking-widest">
            Shortlisting Implementation
          </p>

          <h2 className="text-4xl md:text-5xl font-bold mt-4">
            End-to-End Candidate Decision Flow
          </h2>

          <p className="text-gray-400 mt-6 max-w-3xl mx-auto">
            The workflow receives the candidate ATS score,
            evaluates the configured decision criteria, and
            returns a recruitment status through the API.
          </p>

        </div>

        <div className="grid md:grid-cols-4 gap-6">

          {/* Candidate */}
          <div className="bg-slate-900 border border-blue-500 rounded-2xl p-7">

            <h3 className="text-2xl font-bold text-blue-400">
              👤 Candidate
            </h3>

            <p className="text-gray-400 mt-4">
              Candidate information and evaluation data are submitted
              to the recruitment API.
            </p>

          </div>

          {/* ATS */}
          <div className="bg-slate-900 border border-purple-500 rounded-2xl p-7">

            <h3 className="text-2xl font-bold text-purple-400">
              📊 ATS Score
            </h3>

            <p className="text-gray-400 mt-4">
              The candidate receives an ATS score generated by
              the scoring engine.
            </p>

          </div>

          {/* Decision */}
          <div className="bg-slate-900 border border-yellow-500 rounded-2xl p-7">

            <h3 className="text-2xl font-bold text-yellow-400">
              ⚖️ Decision Logic
            </h3>

            <p className="text-gray-400 mt-4">
              The ATS score is evaluated against the configured
              shortlisting decision rules.
            </p>

          </div>

          {/* Status */}
          <div className="bg-slate-900 border border-green-500 rounded-2xl p-7">

            <h3 className="text-2xl font-bold text-green-400">
              🎯 Status
            </h3>

            <p className="text-gray-400 mt-4">
              The API returns the candidate ID, ATS score,
              recruitment status, and completion message.
            </p>

          </div>

        </div>

      </section>

      {/* Decision Workflow */}
      <section className="max-w-7xl mx-auto px-6 pb-24">

        <div className="text-center mb-12">

          <p className="text-blue-400 uppercase tracking-widest">
            Decision Workflow
          </p>

          <h2 className="text-4xl md:text-5xl font-bold mt-4">
            ATS Score → Recruitment Decision
          </h2>

        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-8 md:p-10">

          <div className="grid md:grid-cols-5 gap-4 items-center text-center">

            <div className="border border-blue-500 rounded-xl p-6">
              <span className="text-3xl">👤</span>

              <h3 className="font-bold mt-3">
                Candidate
              </h3>
            </div>

            <div className="hidden md:block text-gray-500 text-2xl">
              →
            </div>

            <div className="border border-purple-500 rounded-xl p-6">
              <span className="text-3xl">📊</span>

              <h3 className="font-bold mt-3">
                ATS Score
              </h3>
            </div>

            <div className="hidden md:block text-gray-500 text-2xl">
              →
            </div>

            <div className="border border-yellow-500 rounded-xl p-6">
              <span className="text-3xl">⚖️</span>

              <h3 className="font-bold mt-3">
                Decision
              </h3>
            </div>

          </div>

          <div className="flex justify-center text-gray-500 text-2xl my-8">
            ↓
          </div>

          <div className="grid md:grid-cols-3 gap-6">

            {/* Shortlisted */}
            <div className="border border-green-500 rounded-xl p-6 text-center">

              <span className="text-3xl">
                ✅
              </span>

              <h3 className="font-bold text-green-400 text-xl mt-3">
                Shortlisted
              </h3>

              <p className="text-gray-400 mt-2">
                Candidate qualifies for the next recruitment stage.
              </p>

            </div>

            {/* Review */}
            <div className="border border-yellow-500 rounded-xl p-6 text-center">

              <span className="text-3xl">
                🔎
              </span>

              <h3 className="font-bold text-yellow-400 text-xl mt-3">
                Review
              </h3>

              <p className="text-gray-400 mt-2">
                Candidate requires additional recruiter evaluation.
              </p>

            </div>

            {/* Rejected */}
            <div className="border border-red-500 rounded-xl p-6 text-center">

              <span className="text-3xl">
                ❌
              </span>

              <h3 className="font-bold text-red-400 text-xl mt-3">
                Rejected
              </h3>

              <p className="text-gray-400 mt-2">
                Candidate does not meet the configured evaluation criteria.
              </p>

            </div>

          </div>

        </div>

      </section>

      {/* API Validation */}
      <section className="max-w-7xl mx-auto px-6 pb-24">

        <div className="text-center mb-12">

          <p className="text-blue-400 uppercase tracking-widest">
            API Validation
          </p>

          <h2 className="text-4xl md:text-5xl font-bold mt-4">
            Shortlisting Test Results
          </h2>

          <p className="text-gray-400 mt-6 max-w-3xl mx-auto">
            The shortlisting endpoint was tested using different
            ATS score scenarios to verify that the API returns
            the expected recruitment status.
          </p>

        </div>

        <div className="grid md:grid-cols-2 gap-8">

          {/* Review */}
          <div className="bg-slate-900 border border-yellow-500 rounded-2xl p-8">

            <div className="flex justify-between items-center">

              <h3 className="text-2xl font-bold text-yellow-400">
                🔎 Review Scenario
              </h3>

              <span className="px-4 py-2 rounded-full bg-yellow-500/10 text-yellow-400 font-semibold">
                ATS: 60
              </span>

            </div>

            <div className="mt-6 bg-slate-950 rounded-xl p-6">

              <p className="text-gray-500 text-sm mb-3">
                API Response
              </p>

              <pre className="text-sm text-gray-300 whitespace-pre-wrap text-left">
{`{
  "candidate_id": "CAND-82624710",
  "ats_score": 60,
  "status": "review",
  "message": "Candidate shortlisting completed"
}`}
              </pre>

            </div>

            <p className="text-yellow-400 font-semibold mt-5">
              ✓ API response validated
            </p>

          </div>

          {/* Rejected */}
          <div className="bg-slate-900 border border-red-500 rounded-2xl p-8">

            <div className="flex justify-between items-center">

              <h3 className="text-2xl font-bold text-red-400">
                ❌ Rejected Scenario
              </h3>

              <span className="px-4 py-2 rounded-full bg-red-500/10 text-red-400 font-semibold">
                ATS: 40
              </span>

            </div>

            <div className="mt-6 bg-slate-950 rounded-xl p-6">

              <p className="text-gray-500 text-sm mb-3">
                API Response
              </p>

              <pre className="text-sm text-gray-300 whitespace-pre-wrap text-left">
{`{
  "candidate_id": "CAND-82624710",
  "ats_score": 40,
  "status": "rejected",
  "message": "Candidate shortlisting completed"
}`}
              </pre>

            </div>

            <p className="text-red-400 font-semibold mt-5">
              ✓ API response validated
            </p>

          </div>

        </div>

      </section>

      {/* API Response Structure */}
      <section className="max-w-7xl mx-auto px-6 pb-24">

        <div className="text-center mb-12">

          <p className="text-blue-400 uppercase tracking-widest">
            API Contract
          </p>

          <h2 className="text-4xl md:text-5xl font-bold mt-4">
            Shortlisting Response
          </h2>

        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-8 md:p-10">

          <div className="grid md:grid-cols-4 gap-6">

            <div className="border border-blue-500 rounded-xl p-6">

              <h3 className="font-bold text-blue-400">
                candidate_id
              </h3>

              <p className="text-gray-400 mt-3">
                Unique identifier used to track the candidate.
              </p>

            </div>

            <div className="border border-purple-500 rounded-xl p-6">

              <h3 className="font-bold text-purple-400">
                ats_score
              </h3>

              <p className="text-gray-400 mt-3">
                Numerical ATS score produced by the scoring engine.
              </p>

            </div>

            <div className="border border-yellow-500 rounded-xl p-6">

              <h3 className="font-bold text-yellow-400">
                status
              </h3>

              <p className="text-gray-400 mt-3">
                Recruitment decision returned by the shortlisting logic.
              </p>

            </div>

            <div className="border border-green-500 rounded-xl p-6">

              <h3 className="font-bold text-green-400">
                message
              </h3>

              <p className="text-gray-400 mt-3">
                Confirms successful completion of candidate shortlisting.
              </p>

            </div>

          </div>

        </div>

      </section>

      {/* Outcomes */}
      <section className="max-w-7xl mx-auto px-6 pb-24">

        <div className="text-center mb-12">

          <p className="text-blue-400 uppercase tracking-widest">
            Day 19 Outcomes
          </p>

          <h2 className="text-4xl md:text-5xl font-bold mt-4">
            Key Implementation Results
          </h2>

        </div>

        <div className="grid md:grid-cols-3 gap-8">

          <div className="bg-slate-900 border border-blue-500 rounded-2xl p-8">

            <h3 className="text-xl font-bold text-blue-400">
              ATS Integration
            </h3>

            <p className="text-gray-400 mt-4">
              Candidate ATS scores are connected to the
              shortlisting workflow.
            </p>

          </div>

          <div className="bg-slate-900 border border-green-500 rounded-2xl p-8">

            <h3 className="text-xl font-bold text-green-400">
              Automated Decisions
            </h3>

            <p className="text-gray-400 mt-4">
              The system produces a recruitment status based
              on the candidate evaluation score.
            </p>

          </div>

          <div className="bg-slate-900 border border-purple-500 rounded-2xl p-8">

            <h3 className="text-xl font-bold text-purple-400">
              API Validation
            </h3>

            <p className="text-gray-400 mt-4">
              Different candidate score scenarios were tested
              through the API and the returned responses were verified.
            </p>

          </div>

        </div>

      </section>

      {/* Final Section */}
      <section className="max-w-5xl mx-auto px-6 pb-24">

        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-10 text-center">

          <p className="text-blue-400 uppercase tracking-widest">
            Zecpath AI Progress
          </p>

          <h2 className="text-4xl font-bold mt-4">
            From ATS Score to Hiring Decision
          </h2>

          <p className="text-gray-400 mt-5 max-w-3xl mx-auto">
            Day 19 connects the ATS scoring layer with the recruitment
            decision workflow, creating an important step toward an
            end-to-end AI-powered hiring platform.
          </p>

        </div>

      </section>

      <Footer />

    </div>
  );
}

export default Day19;